name: syncflow_example

description: Example app for SyncFlow package

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncflow:
    path: ../

flutter:
  uses-material-design: true